name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    
    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9
    
    - name: Check Nix flake inputs
      uses: DeterminateSystems/flake-checker-action@v2
    
    - name: Build all packages
      run: |
        nix build -L .#xrlinuxdriver
        nix build -L .#breezy-desktop-common
        nix build -L .#breezy-desktop-gnome
        nix build -L .#breezy-desktop-kwin
    
    - name: Run tests
      run: |
        chmod +x tests/run-tests.sh
        ./tests/run-tests.sh
    
    - name: Run flake check
      run: nix flake check