name: Publish to FlakeHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      
      - name: Run Tests
        run: |
          chmod +x tests/run-tests.sh
          ./tests/run-tests.sh
      
      - name: Publish to FlakeHub
        uses: flakehub/upload-flake-action@v1
        with:
          version: ${{ github.ref_name }}
          publish: true